image: "hdus001/cypress-test-runner:80-4.0.1b"

stages:
    - lint
    - test

lint:
    script:
      - make gitlab_lint

test:
  variables:
    ENV: 'production'
  script:
    - make gitlab_test
  artifacts:
    name: "ScreenshotsAndVideos"
    expose_as: "ScreenshotsAndVideos"
    paths:
      - tests/results/
    expire_in: 2 yrs
    when: always
