name: Test Myamaysim

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Test the website
      uses: actions/checkout@v1
      run: make test
      env:
        CYPRESS_baseUrl: https://www.amaysim.com.au